auth:
  postgresPassword: "postgres"
  username: "postgres"
  password: "postgres"
  database: "postgres"
  secretKeys:
    adminPasswordKey: "postgres"
    userPasswordKey: "postgres"
    replicationPasswordKey: "postgres"
