name: microservice-stack-deploy-api
description: Build and publish docker image

inputs:
  app-name:
    description: 'Name of the buildable project'
    required: true
  deployment-chart:
    description: 'Path to deployment chart'
    required: true
  app-values:
    description: 'Path to deployment overrides'
    required: true
  cluster-name:
    description: 'EKS cluster name'
    required: true
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  ecr-repository:
    description: 'ECR repository name'
    required: true
  image-tag:
    description: 'Image tag name'
    required: true
  kube-config-data:
    description: 'Kube config data'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Get Kubeconfig
      id: get-kubeconfig
      shell: bash
      run: |
        aws eks update-kubeconfig --name ${{ inputs.cluster-name }} --region ${{ inputs.aws-region }}
        echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
        echo $(cat ~/.kube/config | base64) >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Deploy
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
      with:
        command: helm upgrade --install ${{ inputs.app-name }} ${{ inputs.deployment-chart }} --values ${{ inputs.deployment-chart }}/values.yaml --values ${{ inputs.app-values }} --set version=${{ inputs.app-name }}-${{ inputs.image-tag }} --set image=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }} --set environment=production
