name: microservice-stack-deploy-api
description: Build and publish docker image

inputs:
  projectName:
    description: 'Name of the buildable project'
    required: true
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  ecr-repository:
    description: 'ECR repository name'
    required: true
  image-tag:
    description: 'Image tag name'
    required: true
  kube-config-data:
    description: 'Kube config data'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Deploy
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube-config-data }}
      with:
        command: helm upgrade --install ${{ inputs.projectName }} ./infrastructure/charts/node-service --values ./infrastructure/charts/node-service/values.yaml --values apps/api/${{ inputs.projectName }}/deployment-values.yaml --set version=${{ inputs.projectName }}-${{ inputs.image-tag }} --set image=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}
