name: Publish

on:
  push:
    tags:
      - v*
jobs:
  extract_metadata:
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.extract.outputs.IMAGE_TAG }}
    steps:
      - id: extract
        run: |
          export TAG=${GITHUB_REF#refs/tags/}
          echo "IMAGE_TAG=${TAG#v}" >> $GITHUB_OUTPUT
  check:
    runs-on: ubuntu-latest
    needs: [extract_metadata]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npm ci
      - run: npx nx workspace-lint
      - run: npx nx run-many --target=lint --all --parallel=3
      - run: npx nx run-many --target=test --all --parallel=3 --ci --code-coverage
      - run: npx nx run-many --target=build --all --parallel=3
      - run: npx nx run-many --target=publish --all --parallel=3 --args="--ver=${{ needs.extract_metadata.outputs.imageTag }}"
